name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Unit Test
      run: dotnet test --configuration Release
      working-directory: Core.Tests
